/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.test.streaming.api.datastream;

import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.api.connector.dsv2.DataStreamV2SourceUtils;
import org.apache.flink.api.connector.dsv2.WrappedSink;
import org.apache.flink.api.connector.source.SourceReaderContext;
import org.apache.flink.connector.datagen.source.DataGeneratorSource;
import org.apache.flink.connector.datagen.source.GeneratorFunction;
import org.apache.flink.datastream.api.ExecutionEnvironment;
import org.apache.flink.datastream.api.common.Collector;
import org.apache.flink.datastream.api.context.RuntimeContext;
import org.apache.flink.datastream.api.extension.join.JoinExtension;
import org.apache.flink.datastream.api.extension.join.JoinFunction;
import org.apache.flink.datastream.api.stream.KeyedPartitionStream;
import org.apache.flink.datastream.api.stream.NonKeyedPartitionStream;
import org.apache.flink.streaming.api.functions.sink.PrintSink;

import java.io.Serializable;
import java.util.Random;

/**
 * This example illustrates an e-commerce scenario where order information is enriched by
 * integrating the order details with express information.
 *
 * <p>The application processes two types of input data: the first is the order information {@link
 * Order}, which includes attributes such as orderId, productId, and others. The second is the
 * express information {@link ExpressEvent}, which contains orderId, expressId, and additional
 * details.
 *
 * <p>The output generated by the application is a more comprehensive order summary {@link
 * EnrichedOrder}, which combines both order and express information.
 *
 * <p>To enrich the orders, we partition the {@link Order} and {@link ExpressEvent} data by orderId.
 * We then join the records from {@link Order} and {@link ExpressEvent} that share the same orderId,
 * then generate and output the {@link EnrichedOrder}.
 */
class EnrichOrderExample implements Serializable {

    private static final int RECORD_NUMBER = 100000;
    private static final int ORDER_NUMBER = 10;

    /** The {@link Order} contains essential order information. */
    public static class Order {
        private long orderId;
        private long productId;
        private long userId;
        private long orderTime;

        public Order(long orderId, long productId, long userId, long orderTime) {
            this.orderId = orderId;
            this.productId = productId;
            this.userId = userId;
            this.orderTime = orderTime;
        }

        public long getOrderId() {
            return orderId;
        }

        public long getProductId() {
            return productId;
        }

        public long getUserId() {
            return userId;
        }

        public long getOrderTime() {
            return orderTime;
        }

        @Override
        public String toString() {
            return "Order{"
                    + "orderId="
                    + orderId
                    + ", productId="
                    + productId
                    + ", userId="
                    + userId
                    + ", purchaseTimestamp="
                    + orderTime
                    + '}';
        }
    }

    /** The {@link ExpressEvent} contains information about the express service. */
    public static class ExpressEvent {
        private long orderId;
        private long expressId;
        private long arrivalTimestamp;

        public ExpressEvent(long orderId, long expressId, long arrivalTimestamp) {
            this.orderId = orderId;
            this.expressId = expressId;
            this.arrivalTimestamp = arrivalTimestamp;
        }

        public long getOrderId() {
            return orderId;
        }

        public long getExpressId() {
            return expressId;
        }

        public long getArrivalTimestamp() {
            return arrivalTimestamp;
        }
    }

    /** The {@link EnrichedOrder} includes both order details and express information. */
    public static class EnrichedOrder {
        private long orderId;
        private long productId;
        private long userId;
        private long orderTime;
        private long expressId;
        private long expressArrivalTimestamp;

        public EnrichedOrder(
                long orderId,
                long productId,
                long userId,
                long orderTime,
                long expressId,
                long expressArrivalTimestamp) {
            this.orderId = orderId;
            this.productId = productId;
            this.userId = userId;
            this.orderTime = orderTime;
            this.expressId = expressId;
            this.expressArrivalTimestamp = expressArrivalTimestamp;
        }

        public long getOrderId() {
            return orderId;
        }

        public long getProductId() {
            return productId;
        }

        public long getUserId() {
            return userId;
        }

        public long getOrderTime() {
            return orderTime;
        }

        public void setExpressId(long expressId) {
            this.expressId = expressId;
        }

        public void setExpressArrivalTimestamp(long expressArrivalTimestamp) {
            this.expressArrivalTimestamp = expressArrivalTimestamp;
        }

        @Override
        public String toString() {
            return "EnrichedOrder{"
                    + "orderId="
                    + orderId
                    + ", productId="
                    + productId
                    + ", userId="
                    + userId
                    + ", orderTime="
                    + orderTime
                    + ", expressId="
                    + expressId
                    + ", expressArrivalTimestamp="
                    + expressArrivalTimestamp
                    + '}';
        }
    }

    public static class ExpressEventGenerateFunction
            implements GeneratorFunction<Long, ExpressEvent> {

        private Random random = new Random();

        @Override
        public void open(SourceReaderContext readerContext) throws Exception {
            random.setSeed(System.currentTimeMillis());
        }

        @Override
        public ExpressEvent map(Long value) throws Exception {
            return new ExpressEvent(
                    random.nextInt(ORDER_NUMBER), random.nextInt(), System.currentTimeMillis());
        }
    }

    public static class OrderGenerateFunction implements GeneratorFunction<Long, Order> {

        private Random random = new Random();

        @Override
        public void open(SourceReaderContext readerContext) throws Exception {
            random.setSeed(System.currentTimeMillis());
        }

        @Override
        public Order map(Long value) throws Exception {
            return new Order(
                    random.nextInt(ORDER_NUMBER),
                    random.nextInt(),
                    random.nextInt(),
                    System.currentTimeMillis());
        }
    }

    public static void main(String[] args) throws Exception {
        ExecutionEnvironment env = ExecutionEnvironment.getInstance();

        // create Order stream source and key by orderId
        KeyedPartitionStream<Long, Order> orderKeyedStream =
                env.fromSource(
                                DataStreamV2SourceUtils.wrapSource(
                                        new DataGeneratorSource<Order>(
                                                new OrderGenerateFunction(),
                                                RECORD_NUMBER,
                                                TypeInformation.of(Order.class))),
                                "OrderSource")
                        .withParallelism(1)
                        .keyBy(Order::getOrderId);

        // create ExpressEvent stream source and key by orderId
        KeyedPartitionStream<Long, ExpressEvent> expressEventKeyedStream =
                env.fromSource(
                                DataStreamV2SourceUtils.wrapSource(
                                        new DataGeneratorSource<ExpressEvent>(
                                                new ExpressEventGenerateFunction(),
                                                RECORD_NUMBER,
                                                TypeInformation.of(ExpressEvent.class))),
                                "ExpressArrivalEventSource")
                        .withParallelism(1)
                        .keyBy(ExpressEvent::getOrderId);

        NonKeyedPartitionStream<EnrichedOrder> enrichedOrderStream =
                // join the order stream and express event stream on orderId
                orderKeyedStream.connectAndProcess(
                        expressEventKeyedStream,
                        JoinExtension.join(
                                (JoinFunction<Order, ExpressEvent, EnrichedOrder>) (order, expressArrivalEvent, output, ctx) -> {
                                    // generate EnrichedOrder and output
                                    output.collect(
                                            new EnrichedOrder(
                                                    order.getOrderId(),
                                                    order.getProductId(),
                                                    order.getUserId(),
                                                    order.getOrderTime(),
                                                    expressArrivalEvent.getExpressId(),
                                                    expressArrivalEvent.getArrivalTimestamp()));
                                },
                                JoinExtension.JoinType.INNER));

        // print result
        enrichedOrderStream.toSink(new WrappedSink<>(new PrintSink<>()));

        env.execute("EnrichOrderExample");
    }
}
