/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.datastream.impl.extension.window.assigner;

import org.apache.flink.api.common.typeinfo.TypeSerializer;
import org.apache.flink.datastream.api.extension.window.assigner.WindowAssigner;
import org.apache.flink.datastream.api.extension.window.trigger.Trigger;
import org.apache.flink.datastream.api.extension.window.window.TimeWindow;
import org.apache.flink.datastream.impl.extension.window.trigger.EventTimeTrigger;
import org.apache.flink.datastream.impl.extension.window.window.TimeWindowImpl;
import org.apache.flink.streaming.api.windowing.assigners.WindowStagger;

import java.time.Duration;
import java.util.Collection;
import java.util.Collections;

/**
 * A special {@link WindowAssigner} for tumbling event time {@link TimeWindow}, ensuring that each
 * element belongs to only one window.
 */
public class TumblingEventTimeWindowsAssigner extends WindowAssigner<Object, TimeWindowImpl> {

    private static final long serialVersionUID = 1L;

    private final long windowSize;

    private final long globalOffset;

    private final WindowStagger windowStagger;

    /** Window offset generated by {@code windowStagger}. */
    private Long staggerOffset = null;

    protected TumblingEventTimeWindowsAssigner(
            long windowSize, long offset, WindowStagger windowStagger) {
        if (Math.abs(offset) >= windowSize) {
            throw new IllegalArgumentException(
                    "TumblingEventTimeWindows parameters must satisfy abs(offset) < windowSize");
        }

        this.windowSize = windowSize;
        this.globalOffset = offset;
        this.windowStagger = windowStagger;
    }

    @Override
    public Collection<TimeWindowImpl> assignWindows(
            Object element, long timestamp, WindowAssigner.WindowAssignerContext context) {
        if (timestamp > Long.MIN_VALUE) {
            if (staggerOffset == null) {
                staggerOffset =
                        windowStagger.getStaggerOffset(
                                context.getCurrentProcessingTime(), windowSize);
            }
            // Long.MIN_VALUE is currently assigned when no timestamp is present
            long start =
                    TimeWindowImpl.getWindowStartWithOffset(
                            timestamp, (globalOffset + staggerOffset) % windowSize, windowSize);
            return Collections.singletonList(new TimeWindowImpl(start, start + windowSize, true));
        } else {
            // TODO update error message
            throw new RuntimeException(
                    "Record has Long.MIN_VALUE timestamp (= no timestamp marker). "
                            + "Is the time characteristic set to 'ProcessingTime', or did you forget to call "
                            + "'DataStream.assignTimestampsAndWatermarks(...)'?");
        }
    }

    @Override
    public Trigger<Object, TimeWindowImpl> getDefaultTrigger() {
        return EventTimeTrigger.create();
    }

    @Override
    public String toString() {
        return "TumblingEventTimeWindowsAssigner(" + windowSize + ")";
    }

    @Override
    public TypeSerializer<TimeWindowImpl> getWindowSerializer() {
        return new TimeWindowImpl.Serializer();
    }

    @Override
    public boolean isEventTime() {
        return true;
    }

    /**
     * Creates a new {@code TumblingEventTimeWindows} {@link WindowAssigner} that assigns elements
     * to time windows based on the element timestamp.
     *
     * @param windowSize The size of the generated windows.
     * @return The created window assigner.
     */
    public static TumblingEventTimeWindowsAssigner of(Duration windowSize) {
        return new TumblingEventTimeWindowsAssigner(
                windowSize.toMillis(), 0, WindowStagger.ALIGNED);
    }

    /**
     * Creates a new {@code TumblingEventTimeWindows} {@link WindowAssigner} that assigns elements
     * to time windows based on the element timestamp and offset.
     *
     * <p>For example, if you want window a stream by hour,but window begins at the 15th minutes of
     * each hour, you can use {@code of(Time.hours(1),Time.minutes(15))},then you will get time
     * windows start at 0:15:00,1:15:00,2:15:00,etc.
     *
     * <p>Rather than that,if you are living in somewhere which is not using UTC±00:00 time, such as
     * China which is using UTC+08:00,and you want a time window with size of one day, and window
     * begins at every 00:00:00 of local time,you may use {@code of(Time.days(1),Time.hours(-8))}.
     * The parameter of offset is {@code Time.hours(-8))} since UTC+08:00 is 8 hours earlier than
     * UTC time.
     *
     * @param windowSize The size of the generated windows.
     * @param offset The offset which window start would be shifted by.
     */
    public static TumblingEventTimeWindowsAssigner of(Duration windowSize, Duration offset) {
        return new TumblingEventTimeWindowsAssigner(
                windowSize.toMillis(), offset.toMillis(), WindowStagger.ALIGNED);
    }

    /**
     * Creates a new {@code TumblingEventTimeWindows} {@link WindowAssigner} that assigns elements
     * to time windows based on the element timestamp, offset and a staggering offset, depending on
     * the staggering policy.
     *
     * @param windowSize The size of the generated windows.
     * @param offset The globalOffset which window start would be shifted by.
     * @param windowStagger The utility that produces staggering offset in runtime.
     */
    public static TumblingEventTimeWindowsAssigner of(
            Duration windowSize, Duration offset, WindowStagger windowStagger) {
        return new TumblingEventTimeWindowsAssigner(
                windowSize.toMillis(), offset.toMillis(), windowStagger);
    }
}
